x-environment:
  &shared-environment # Pass to build environments and containers for all services
  API_DOMAIN: &api-domain ""
  APP_DOMAIN: &app-domain ""
  APP_TITLE: &app-title "Architecture Identifier"
  APP_DESCRIPTION: &app-description "Identify architectural style with machine learning"
  APP_GITHUB_URL: &app-github-url "https://github.com/garytyler/arch-id-web"
  APP_AUTHOR_NAME: &author-name "Gary Tyler"
  APP_AUTHOR_URL: &author-url "https://github.com/garytyler"
  TENSORBOARD_URL: &tensorboard-url "https://github.com/garytyler/arch-id-web"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production
    environment:
      REACT_APP_API_DOMAIN: *api-domain
      REACT_APP_APP_DOMAIN: *app-domain
      REACT_APP_APP_TITLE: *app-title
      REACT_APP_APP_DESCRIPTION: *app-description
      REACT_APP_APP_GITHUB_URL: *app-github-url
      REACT_APP_AUTHOR_NAME: *author-name
      REACT_APP_AUTHOR_URL: *author-url
      REACT_APP_TENSORBOARD_URL: *tensorboard-url
    ports:
      - 3000:3000

  backend:
    container_name: backend
    environment:
      POETRY_VERSION: 1.1.11
    build:
      context: ./backend
      target: production
    command:
      [
        "gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "-c",
        "./gunicorn_conf.py",
        "app.main:app",
      ]
    ports:
      - 8000:8000
    links:
      - models
    volumes:
      - ./backend:/srv/backend

  models:
    container_name: models
    image: tensorflow/serving:latest
    ports:
      - 8500:8500
      - 8501:8501
    command:
      - --model_config_file=/config/models.prod.config
      - --model_config_file_poll_wait_seconds=300
      - --rest_api_timeout_in_ms=30000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
    volumes:
      - ./config:/config

volumes:
  postgres_data: null
