services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - 3000:3000

  predict:
    image: tensorflow/serving:latest-gpu
    ports:
      - 8501:8501
    environment:
      - MODEL_BASE_PATH=/models
    volumes:
      - ./models:/models
