x-shared-environment:
  &shared-environment # Pass to build environments and containers for all services
  APP_NAME: &app-name "Architecture Recognizer"
  APP_DESC: &app-description ""
  # dns
  DOMAIN:
  # postgres
  POSTGRES_HOST:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:

services:
  backend:
    container_name: backend
    environment:
      <<: *shared-environment
      POETRY_VERSION: 1.1.11
      DEBUG: 0
      SECRET_KEY:
      ALLOWED_HOSTS:
      BACKEND_CORS_ORIGINS:
    build:
      context: ./backend
      target: prod-stage
    command: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "./gunicorn_conf.py", "app.main:app" ]
    ports:
      - 8000:8000
    depends_on:
      # - frontend
      - postgres

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    environment:
      <<: *shared-environment
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      <<: *shared-environment
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
    depends_on:
      - postgres

volumes:
  postgres_data: null
