services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production
    command: s3 cp --recursive /aws s3://${FRONTEND_S3_BUCKET_NAME}/
    environment:
      - NODE_ENV="production"
      - AWS_ACCESS_KEY_ID=${FRONTEND_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${FRONTEND_AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${FRONTEND_AWS_DEFAULT_REGION}

  backend:
    container_name: backend
    build:
      context: ./backend
      target: production
    command:
      [
        "gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "-c",
        "./gunicorn_conf.py",
        "app.main:app",
      ]
    environment:
      - POETRY_VERSION=1.1.11
      - BACKEND_PROJECT_TITLE=${PROJECT_TITLE}
      - BACKEND_CORS_ORIGINS='["*"]'
      - BACKEND_ALLOWED_HOSTS='["*"]'
      - BACKEND_MODELS_SERVER_URL=https://models.architectureid.app
    links:
      - models
    volumes:
      - ./backend:/srv/backend

  models:
    container_name: models
    image: tensorflow/serving:latest
    command:
      - --model_config_file=/config/models.prod.config
      - --model_config_file_poll_wait_seconds=300
      - --rest_api_timeout_in_ms=30000
    ports:
      - 8501:8501
    environment:
      - AWS_ACCESS_KEY_ID=${MODELS_AWS_ACCESS_KEY_ID}
      - AWS_REGION=${MODELS_AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${MODELS_AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${MODELS_S3_ENDPOINT}
    volumes:
      - ./config:/config
