services:
  frontend:
    build:
      target: development
    volumes:
      - .:/srv
      - node_modules_data:/srv/frontend/node_modules

  backend:
    build:
      target: development
    command: /bin/bash -c "python -m uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - .:/srv

  models:
    command:
      - --model_config_file=/config/models.dev.config
    volumes:
      - ./models:/models

volumes:
  node_modules_data:
