services:
  frontend:
    build:
      target: development
    volumes:
      - .:/srv
      - node_modules_data:/srv/frontend/node_modules
    environment:
      - "REACT_APP_API_DOMAIN=localhost:8000"
      - "REACT_APP_DOMAIN=localhost:3000"

  backend:
    build:
      target: development
    command: /bin/bash -c "python -m uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload"      
    volumes:
      - .:/srv

  models:
    command:
      - --model_config_file=/config/models.dev.config
    volumes:
      - ./models:/models

volumes:
  node_modules_data:
