export const CLASS_NAMES: string[] = [
  "Achaemenid",
  "American Foursquare",
  "American craftsman style",
  "Ancient Egyptian",
  "Art Deco",
  "Art Nouveau",
  "Baroque",
  "Bauhaus",
  "Beaux-Arts",
  "Byzantine",
  "Chicago school",
  "Colonial",
  "Deconstructivism",
  "Edwardian",
  "Georgian",
  "Gothic",
  "Greek Revival",
  "International style",
  "Novelty",
  "Palladian",
  "Postmodern",
  "Queen Anne",
  "Romanesque",
  "Russian Revival",
  "Tudor Revival",
];
